import type { Metadata } from "next";
import { Manrope, Poppins } from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
  title: "Andrew's Website",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900']
})

const manrope = Manrope({
  subsets: ['latin'],
  weight: ["200", "300", "400", "500", "600", "700", "800"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
